api-service:
  http:
    addr: "127.0.0.1:8084"
agent:
  addr: "127.0.0.1:8082"
  useTLS: false
  grpcServerName: ""
data-provider:
  addr: "127.0.0.1:8083"
  useTLS: false
  grpcServerName: ""
grpc-client:
  caCert: ""
  clientCert: ""
  clientKey: ""